# Generated by Django 3.0.6 on 2020-08-28 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.SlugField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=4000)),
                ('assignment_link', models.URLField(blank=True, null=True)),
                ('answer_link', models.URLField(blank=True, null=True)),
                ('answer_post_time', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_created', to=settings.AUTH_USER_MODEL)),
                ('users_completed', models.ManyToManyField(related_name='assignments_completed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
