# Generated by Django 3.0.6 on 2020-08-28 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('month', models.CharField(max_length=30)),
                ('weekday', models.CharField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=30, unique=True)),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=40)),
                ('attendance_taken', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(related_name='events_attended', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_set', to='schedule.Day')),
                ('users_attending', models.ManyToManyField(related_name='events_marked_attending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
